package org.umg.compiladores;

import java_cup.runtime.Symbol;

parser code 
{:
    private Symbol symbol;

    public void syntax_error(Symbol s) {
        this.symbol = s;
    }

    public Symbol getSymbol(){
        return this.symbol;
    }
:};

terminal RESERVADAS, OPERADOR, AGRUPADOR, SIMBOLO,
    IDENTIFICADOR, NUMERO, ERROR;
non terminal INICIO;

start with INICIO;

INICIO ::= OPERADOR
;



